defaults:
  - algorithm: ppo
  - platform: bwuni_gpu_4
  - _self_

env_name: CartPole-v1
total_steps: 100000
total_epochs: 300
device: cuda

wandb:
  use: True
  project: rl_test
  group: bwuni

seed: ???
n_steps: ???

hydra:
  sweeper:
    params:
      seed: 0, 1, 2  # starts 3 jobs sequentially, overwrites seed value
      n_steps: 10, 100, 1000

